# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20180519_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_profile',
            name='car_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Car'),
        ),
        migrations.AlterField(
            model_name='driver_profile',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Location'),
        ),
        migrations.AlterField(
            model_name='driver_profile',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_review', to='driver.Review'),
        ),
    ]
