# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20180520_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_num',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='driver_profile',
            name='license_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
