# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_auto_20180519_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('national_ID', models.DecimalField(decimal_places=2, max_digits=50)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='driver.Location')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_pickup', to='driver.Location')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_review', to='driver.Review')),
            ],
            options={
                'ordering': ['pickup_location'],
            },
        ),
    ]
