# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20180521_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider_profile',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='driver.Location'),
        ),
        migrations.AlterField(
            model_name='rider_profile',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_pickup', to='driver.Location'),
        ),
        migrations.AlterField(
            model_name='rider_profile',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_review', to='driver.Review'),
        ),
    ]
